# Site settings
course_name: Engineering Societal Systems
course_description: "This class will explore topics in the intersection of computer science, economics, and operations -- on the application of algorithms, data science/machine learning, and mechanism design to the study of democracy, markets, and societal systems at large.
Methodological tools discussed include mathematical (mechanism/market design, social choice, pricing, matching, etc), empirical (large-scale optimization, demand estimation, using governmental data, etc), and conceptual. Application domains could include markets (labor, accommodation, services, rides), governmental (transportation, democracy) and other non-profit settings (education, housing, humanitarian, volunteer coordination, food allocation).

The 2025 offering will focus on algorithms in government and admissions/hiring in particular.

The course is accessible and of interest to students across ORIE, CS, IS, and Johnson. Assignments will be paper reading, presentations, and a research project, and students will have methodological flexibility.
"
course_semester: "Spring 2025"

baseurl: "/Spring2025" # the subpath of your site, e.g. /blog/
url: "http://ORIE6170.github.io/" # the base hostname & protocol for your site

schoolname: "Cornell Tech"
schoolurl: "https://tech.cornell.edu/"
twitter_username:

address: Cornell Tech, NYC, NY

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-Z5E5R5LFRG

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop', vendor]

dateformat: "%m/%d"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
