# Site settings
course_name: Engineering Societal Systems
course_description: "This seminar class will explore topics in the intersection of computer science, economics, and operations -- on the application of algorithms, data science/machine learning, and market design to the study of democracy, markets, and societal systems at large. This year, we will especially focus on the theme of computational systems in government, education, and related high-stakes settings, broken down into four kinds of systems: matching/recommendation, prediction, optimization, pricing.

The goal is for the class to be methodologically appropriate for a diverse set of students, including in ORIE, CS, and IS. The assignments will have substantial flexibility for you to choose the methodological toolkit that is most appropriate for your research and goals. The paper discussions and in class lectures will also aim to be broadly accessible and interesting."
course_semester: "Spring 2025"

baseurl: "/Spring2025" # the subpath of your site, e.g. /blog/
url: "http://ORIE6170.github.io/" # the base hostname & protocol for your site

schoolname: "Cornell Tech"
schoolurl: "https://tech.cornell.edu/"
twitter_username:

address: Cornell Tech, NYC, NY

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-Z5E5R5LFRG

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop', vendor]

dateformat: "%m/%d"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
